// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3_oJpd9NCV-tbcYZ24Oes41GLOgjFAFA',
    appId: '1:674956588315:web:7e327b322f43d4e1458fbe',
    messagingSenderId: '674956588315',
    projectId: 'bidhood-api',
    authDomain: 'bidhood-api.firebaseapp.com',
    databaseURL: 'https://bidhood-api-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bidhood-api.appspot.com',
    measurementId: 'G-GNZF7STP2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRcYIqDSD--TxsfS-pTsVldtMul74pRXY',
    appId: '1:674956588315:android:934f236a6d2b96be458fbe',
    messagingSenderId: '674956588315',
    projectId: 'bidhood-api',
    databaseURL: 'https://bidhood-api-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bidhood-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD43R48abpULvWEpL-cT9Fzg11goU59cYg',
    appId: '1:674956588315:ios:055fa3b2a7d6ae65458fbe',
    messagingSenderId: '674956588315',
    projectId: 'bidhood-api',
    databaseURL: 'https://bidhood-api-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bidhood-api.appspot.com',
    iosBundleId: 'com.example.bidhood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD43R48abpULvWEpL-cT9Fzg11goU59cYg',
    appId: '1:674956588315:ios:055fa3b2a7d6ae65458fbe',
    messagingSenderId: '674956588315',
    projectId: 'bidhood-api',
    databaseURL: 'https://bidhood-api-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bidhood-api.appspot.com',
    iosBundleId: 'com.example.bidhood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3_oJpd9NCV-tbcYZ24Oes41GLOgjFAFA',
    appId: '1:674956588315:web:fe1bca9ed4518b69458fbe',
    messagingSenderId: '674956588315',
    projectId: 'bidhood-api',
    authDomain: 'bidhood-api.firebaseapp.com',
    databaseURL: 'https://bidhood-api-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bidhood-api.appspot.com',
    measurementId: 'G-MT16W8J8ZF',
  );
}
